---
title: "Relationships between two variables"
subtitle: "REFERENCE SHEET"
format: 
  pdf:
    toc: true
    toc-depth: 5
execute:
  message: false
  warning: false
  echo: false
  fig-width: 8
  fig-height: 4
---

improving timeseries plots
birds: color by migratory or non-migratory? or by genus
change this to vegetation

```{r}
library(ggrepel)
library(tidyverse)
library(janitor)

birds <- read_csv("https://raw.githubusercontent.com/ENVS-193DD/datasets/refs/heads/main/birds/birds.csv")

weather <- read_csv("https://raw.githubusercontent.com/ENVS-193DD/datasets/refs/heads/main/weather/4310193.csv") |> 
  clean_names() |> 
  mutate(month = month(date)) |> 
  group_by(month) |> 
  mutate(total_monthly_precip_in = sum(prcp, na.rm = TRUE),
         mean_monthly_tmax_f = mean(tmax, na.rm = TRUE)) |> 
  ungroup() |> 
  select(date, total_monthly_precip_in, mean_monthly_tmax_f) |> 
  distinct()
  

shorebirds_wy2025 <- birds |> 
  filter(e_bird_group == "Shorebirds" &
           between(observation_date, as_date("2024-10-01"), as_date("2025-09-30"))) |> 
  group_by(observation_date, species) |> 
  summarize(total = sum(count)) |> 
  ungroup() |> 
  # taking out species only seen once
  filter(!(species %in% c("Peep sp.", "Sandpiper sp.", "Dowitcher sp.", 
                          "Wilson's Snipe", "Red-necked Phalarope"))) |> 
  complete(observation_date, species,
           fill = list(total = 0)) |> 
  mutate(family = case_when(
    species %in% c("Black-necked Stilt") ~ "Recurvirostridae",
    species %in% c("Greater Yellowlegs", "Killdeer", 
                   "Least Sandpiper", "Long-billed Dowitcher", 
                   "Western Sandpiper") ~ "Scolopacidae",
    species %in% c("Semipalmated Plover") ~ "Charadriidae"
  )) |> 
  group_by(species) |> 
  mutate(species_label = case_when(
    observation_date == min(observation_date) ~ species
  )) |> 
  ungroup() |> 
  left_join(weather, by = c("observation_date" = "date"))

shorebirds_all <- birds |> 
  filter(e_bird_group == "Shorebirds") |> 
  group_by(observation_date, species) |> 
  summarize(total = sum(count)) |> 
  ungroup() |> 
  # taking out species only seen once
  # filter(!(species %in% c("Peep sp.", "Sandpiper sp.", "Dowitcher sp.", 
  #                         "Wilson's Snipe", "Red-necked Phalarope"))) |> 
  complete(observation_date, species,
           fill = list(total = 0)) |> 
  mutate(family = case_when(
    species %in% c("Black-necked Stilt") ~ "Recurvirostridae",
    species %in% c("Greater Yellowlegs", "Killdeer", 
                   "Least Sandpiper", "Long-billed Dowitcher", 
                   "Western Sandpiper", "Wilson's Snipe", "Red-necked Phalarope") ~ "Scolopacidae",
    species %in% c("Semipalmated Plover") ~ "Charadriidae"
  )) |> 
  group_by(species) |> 
  mutate(species_label = case_when(
    observation_date == max(observation_date) ~ species
  )) |> 
  ungroup() |> 
  left_join(weather, by = c("observation_date" = "date"))
```

```{r}
#| fig-height: 4
#| fig-width: 10
ggplot(data = shorebirds_wy2025,
       mapping = aes(x = observation_date,
                     y = total,
                     color = family,
                     group = species)) +
  geom_point() +
  geom_line() +
  scale_x_date(expand = expansion(mult = c(0.3, 0.1)),
               limits = c(as_date("2024-10-01"), NA),

               breaks = as_date(c("2024-10-01", "2025-01-01", "2025-03-01", "2025-06-01", "2025-09-01")),
               date_labels = "%B") +
  scale_y_continuous(expand = expansion(mult = c(0.01, 0.01))) +
  geom_text_repel(mapping = aes(label = species_label),
                  seed = 100,
                  # right align labels
                  hjust = 1,
                  # repel in y direction only
                  direction = "y",
                  # linetype
                  segment.linetype = 3,
                  # nudge starting point 5 units to left
                  nudge_x = -1,
                  nudge_y = 1,
                  # width
                  segment.size = 0.5,
                  #max.overlaps = Inf,
                  force = 0.5,
                  xlim  = as_date("2024-10-01"),
                  show.legend = FALSE) +
  theme(panel.background = element_blank(),
        panel.grid = element_blank())

ggplot(data = shorebirds_all,
       mapping = aes(x = mean_monthly_tmax_f,
                     y = total)) +
  geom_point() +
  facet_wrap(~ species,
             scales = "free_y")
```

